### ISSUE TITLE
Problem with the footer

### ISSUE THREAD

**Issue by shreyshreyansh** [hidimpu/Weather#1]
As you can see the footer is not in right position

![Screenshot 2021-08-18 110109](https://user-images.githubusercontent.com/53744971/129842739-d2bd6eb9-c7ce-4a1f-91ef-fe7f52d39b45.png)

What you can so is : 

![Screenshot 2021-08-18 110123](https://user-images.githubusercontent.com/53744971/129842765-7ecbefa1-1566-4c91-a664-c17be21e1fde.png)

**Comment by hidimpu** [comment]
I will fix it soon buddy, currently focus is on the placements
Would you like to make a pull request for the fix if you have time?

**Comment by shreyshreyansh** [comment]
> I will fix it soon buddy, currently focus is on the placements
> Would you like to make a pull request for the fix if you have time?

Ok i will make a PR
